
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG